### ISSUE TITLE
Bugs and unexpected behaviour on user management

### ISSUE THREAD

**Issue by vchain-us-mgmt** [codenotary/immudb#164] opened 2020-05-08 12:45 UTC
The following bugs were identified while testing immuadmin user command:
1) on Linux when immudb is started as a normal process the command "./immuadmin user --create <username>": it creates a user with a password instead of requesting the user to type in his password. This is the expected behavior for admin users, not for additional users
2) On Linux when immudb is started as a service the command "./immuadmin user --create <username>": the command fails
3) On Windows the command "./immuadmin user --create <username>" fails both when immudb is started as a service or as a background process
4) "immuadmin user immu change-password" is not working 
5) "immuadmin login immu" the password is going to the new line, like if the user has already entered the password

**Comment by padurean** [comment] 2020-05-08 22:06
- [x] **1. FIXED**
- [ ] 2. I probably have to investigate it with @mmeloni 
- [ ] 3. Same as 2. @vchain-us-mgmt: If possible please provide also the error message.
- [x] 4. I've implemented a **possible fix** (i could not reproduce it though)
- [x] 5. Same as 4.: **please re-test**.

**NOTE**: These fixes & changes are available only on the `fix/user-management` branch at the moment.

**Comment by padurean** [comment] 2020-05-09 23:20
@vchain-us-mgmt Please re-test again all the flow with feature branch `fix/user-management` (not merged yet into master).
- Please note that variables names have been changed - see how they should be in CLIs help. At the moment i didn't find a better solution to get them working (their names have match some [viper](https://github.com/spf13/viper) convention, apparently, as their reading is done by this library and it happens during fallback between env vars, .ini` config and [cobra](https://github.com/spf13/cobra) CLI flags)
- In order to reproduce a first-time experience of a new user, please make sure to call `./immuadmin logout` so that the token file is deleted (this affects whether one gets a password prompt or not during the first-time-ever admin with `immu` admin user, as the password is generated by the server in this case so it doesn't make sense to ask for a password input from user; if the token file is present, it will ask for a password though, as it will consider it can't be the first admin login ever).

**Closed** 2020-05-11 16:57 UTC
Labels: back-end, bug
